// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUjghb66wy6Ozzw3ugVuyIljt9q-kVMcg',
    appId: '1:34283703414:web:3dd7c03b6920572d0ee357',
    messagingSenderId: '34283703414',
    projectId: 'security-app-9f004',
    authDomain: 'security-app-9f004.firebaseapp.com',
    storageBucket: 'security-app-9f004.firebasestorage.app',
    measurementId: 'G-YBF09ZB6E1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMrft9kU6L0kgRhUYuXETeR4yUggj1pIY',
    appId: '1:34283703414:android:fb087b0068305a140ee357',
    messagingSenderId: '34283703414',
    projectId: 'security-app-9f004',
    storageBucket: 'security-app-9f004.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD2nnqNGkreUHwmSeWhPiOwaJwNKB-SV0',
    appId: '1:34283703414:ios:1d4c460edac836fd0ee357',
    messagingSenderId: '34283703414',
    projectId: 'security-app-9f004',
    storageBucket: 'security-app-9f004.firebasestorage.app',
    iosBundleId: 'com.example.securityApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDD2nnqNGkreUHwmSeWhPiOwaJwNKB-SV0',
    appId: '1:34283703414:ios:1d4c460edac836fd0ee357',
    messagingSenderId: '34283703414',
    projectId: 'security-app-9f004',
    storageBucket: 'security-app-9f004.firebasestorage.app',
    iosBundleId: 'com.example.securityApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUjghb66wy6Ozzw3ugVuyIljt9q-kVMcg',
    appId: '1:34283703414:web:8288b7b4ad0aafd50ee357',
    messagingSenderId: '34283703414',
    projectId: 'security-app-9f004',
    authDomain: 'security-app-9f004.firebaseapp.com',
    storageBucket: 'security-app-9f004.firebasestorage.app',
    measurementId: 'G-WFQ5GWEHVR',
  );
}
